# code below is taken from https://github.com/fchollet/keras/blob/master/.travis.yml
sudo: required
dist: trusty
language: python
python: # Only two versions for now
  - "2.7"
  - "3.5"
# command to install dependencies
# command to install dependencies
install: "pip install -r requirements.txt"

script:
#  - sed -i -- 's/range(100)/range(1)/g' ??_*.py # change range to 1 for quick testing
  - python lab-07-2-learning_rate_and_evaluation.py # run this first to download the MNIST file
  # run all python files in parallel, http://stackoverflow.com/questions/5015316
  - ls *lab-*.py|xargs -n 1 -P 3 python
  - pytest
